### ISSUE TITLE
FirebaseError: Firebase: Error (auth/invalid-api-key).

### ISSUE THREAD

**Issue by mdestafadilah** [massoudmaboudi/docusaurus-auth-firebase#4]
I try to build with vercel.app , add some additionan environtment, like below

![30-05-2023 14-31-09](https://github.com/massoudmaboudi/docusaurus-auth-firebase/assets/5575882/321698f0-3235-4d78-a44e-f7076f8f4ede)

I read your suggestion to gitignore `.env.local` but vercel need it. so i remov .env.local from ignore file.

Still investigesting, this is vercel.app issues or something else, cz, i'm build locally it's normal.

**Comment by massoudmaboudi** [comment]
The `.env.local `is for your local development. No need to remove it from `.ignore` file since it will upload your sensitive information to your repo and if your repo is public, you are exposing your Firebase API keys to the public.

Though, you need to import the env variables to Vercel as you did in the image you shared.
I suggest revealing and sharing your values from the image above and then taking a screenshot and the same from your Firebase console so I can compare and help.

_**Tip: I think you included an extra character like double quotes at the beginning and the end of each env variable**_ and that is causing the error.

Make sure to change them after your issue is resolved.

**Comment by mdestafadilah** [comment]
Hi, 

I solved my problem with add *.env.local* in private repo.
